"""Top-level CLI for the prompt-library.

Subcommands:
    python cli.py evals [tasks...]   # run the eval harness (mock by default)
    python cli.py index              # regenerate prompts/INDEX.md from frontmatter
    python cli.py list               # print the prompt catalog to stdout
    python cli.py improve "<prompt>" # diagnose & rewrite a weak prompt (offline)
"""

from __future__ import annotations

import argparse
import sys

from evals.promptio import PROMPTS_DIR, iter_prompts

INDEX_PATH = PROMPTS_DIR / "INDEX.md"


def build_index_rows() -> list[tuple[str, str, str, str]]:
    rows = []
    for p in iter_prompts():
        rel = p.path.relative_to(PROMPTS_DIR.parent)
        link = f"[{p.name}]({rel.as_posix()})"
        rows.append((link, p.category, p.version, p.intent))
    return rows


def render_index(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Prompt Library Index",
        "",
        "Auto-generated by `python cli.py index`. Do not edit by hand.",
        "",
        f"**{len(rows)} prompts** across "
        f"{len({r[1] for r in rows})} categories.",
        "",
        "| Name | Category | Version | Intent |",
        "| --- | --- | --- | --- |",
    ]
    for name, category, version, intent in rows:
        intent_cell = intent.replace("|", "\\|")
        lines.append(f"| {name} | `{category}` | {version} | {intent_cell} |")
    lines.append("")
    return "\n".join(lines)


def cmd_index(_args) -> int:
    rows = build_index_rows()
    INDEX_PATH.write_text(render_index(rows), encoding="utf-8")
    print(f"Wrote {INDEX_PATH} ({len(rows)} prompts).")
    return 0


def cmd_list(_args) -> int:
    for name, category, version, intent in build_index_rows():
        print(f"{category:<18} {version:<8} {name}")
        print(f"{'':<27} {intent}")
    return 0


def cmd_evals(args) -> int:
    from evals.run import run

    run(args.tasks or None, force_mock=args.mock, use_table=not args.no_table)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="prompt-library CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    p_index = sub.add_parser("index", help="regenerate prompts/INDEX.md")
    p_index.set_defaults(func=cmd_index)

    p_list = sub.add_parser("list", help="print prompt catalog")
    p_list.set_defaults(func=cmd_list)

    p_eval = sub.add_parser("evals", help="run the eval harness")
    p_eval.add_argument("tasks", nargs="*")
    p_eval.add_argument("--mock", action="store_true")
    p_eval.add_argument("--no-table", action="store_true")
    p_eval.set_defaults(func=cmd_evals)

    from improver.cli import add_parser as add_improve_parser

    add_improve_parser(sub)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
